### ISSUE TITLE
如何理解论文中提到的线性复杂度？

### ISSUE THREAD

**Issue by IDKiro** [fudan-zvg/SOFT#5]
很抱歉我图方便直接用中文提问。

论文里线性开销的关键在于用stride conv下采样，但是conv训练完以后kernel size和stride就固定了，那采样的比例也固定了。
那么训练完以后，如果用更长的序列进行测试，m的长度会随着序列长度n增长，复杂度还是O(n^2)而不是O(n)。
我看了下openreview的审稿意见，似乎有审稿人问到这问题，但rebuttal中提到固定m=49，但当测试序列更长时，这似乎在不改变stride的情况下是无法做到的？感觉Nystromformer的adaptive pooling更符合landmark的意义。
另外，用于生成landmark的conv后面还跟着norm和GELU，是不是这才是收敛的关键？

**Comment by YJHMITWEB** [comment]
Thanks for your interest in this work. 

To your concerns:
First, we adopt average sampling as the sampling strategy which exhibits the same accuracy with less computation, as we stated in Line. 263~264 and discussed in Table. 4(b). In this case, the downsampling rate is variable since there is no parameter in this step, which can be called "adaptive pooling". 

Second, norm and GELU are both the most essential and widely used operations in Transformers as well as other structures with very little computation but to enhance the capacity of the network, so the adoption of them is natural. More to this, in Table. 4(b), random sampling and biased sampling are implemented without norm nor GELU, while both are able to deliver comparable performance. That is to say, for tasks and experiments we explored in this work, the Gaussian kernel, the Nystrom method, and the overall design of the network module are the keys to the success of SOFT.

**Comment by YJHMITWEB** [comment]
Thanks for your interest in this work.

To your concerns:
First, we adopt average sampling as the sampling strategy which exhibits the same accuracy with less computation, as we stated in Table. 4(b) and discussed in 4.4-Token Sampling. In this case, the downsampling ratio is variable since there is no parameter in this step, which can be called "adaptive pooling". Accordingly, the complexity of the model can remain as O(n) by adjusting the downsampling ratio when the sequence length increases.

Second, norm and GELU are both the most essential and widely used operations in Transformers as well as other structures with very little computation but to enhance the capacity of the network, so the adoption of them is natural. More to this, in Table. 4(b), random sampling and biased sampling are implemented without norm nor GELU, while both are able to deliver comparable performance.
